[package]
name = "chains-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# 本地路径依赖到 chains SDK 项目
chains-sdk = { path = "../chains" }

# 用于异步 main 函数
tokio = { version = "1.0", features = ["full"] }

serde_json = "1.0"
